package by.htp.ishop.controller;

public enum CommandName {
	
	REGISTRATION, 
	AUTHORIZATION, 
	GO_TO_MAIN_PAGE, 
	GO_TO_INDEX_PAGE,
	GO_TO_REGISTRATION_SUCCESS_PAGE,
	GO_TO_AUTHORIZATION_PAGE,
	CHANGE_LOCAL, 
	CHANGE_USER_STATUS, 
	WRONG_REQUEST

}
