package by.htp.ishop.controller;

public enum CommandName {
	
	REGISTRATION, 
	AUTHORIZATION,
	ADD_TO_CART,
	GO_TO_INDEX_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_REGISTRATION_SUCCESS_PAGE,
	GO_TO_AUTHORIZATION_PAGE,
	GET_PRODUCTS_BY_CATEGORY,
	GET_PRODUCT,
	GET_CART,
	REDUCE_QUANTITY_PRODUCT,
	INCREASE_QUANTITY_PRODUCT,
	DELETE_PRODUCT_FROM_CART,
	CHANGE_LOCAL, 
	CHANGE_USER_STATUS, 
	SIGN_OUT,
	CLOSE_POPUP

}
